weather_dbt:
  outputs:
    dev:
      dbname: weatherdb
      host: localhost
      pass: tharusha1996
      port: 5432
      schema: analytics
      threads: 1
      type: postgres
      user: postgres
  target: dev
