name: Weather Pipeline

on:
  schedule:
    - cron: '0 * * * *'   # hourly; adjust to your API limits
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      # Point dbt to the temp profile dir we’ll generate
      DBT_PROFILES_DIR: ${{ github.workspace }}/.dbt

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ── Generate profiles.yml from secrets (NOT committed to repo) ──
      - name: Create dbt profile (no file in repo)
        env:
          DBT_HOST:     ${{ secrets.DBT_HOST }}
          DBT_USER:     ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_DBNAME:   ${{ secrets.DBT_DBNAME }}
          DBT_SCHEMA:   ${{ secrets.DBT_SCHEMA }}
          DBT_PORT:     ${{ secrets.DBT_PORT }}
          DBT_SSLMODE:  ${{ secrets.DBT_SSLMODE }}
        run: |
          mkdir -p "$DBT_PROFILES_DIR"
          cat > "$DBT_PROFILES_DIR/profiles.yml" <<EOF
          weather_dbt:
            target: ci
            outputs:
              ci:
                type: postgres
                host: ${DBT_HOST}
                user: ${DBT_USER}
                password: ${DBT_PASSWORD}
                port: ${DBT_PORT}
                dbname: ${DBT_DBNAME}
                schema: ${DBT_SCHEMA}
                sslmode: ${DBT_SSLMODE}
          EOF

      - name: Run ingestion script
        env:
          WEATHERSTACK_API_KEY: ${{ secrets.WEATHERSTACK_API_KEY }}
          DB_URL: ${{ secrets.DB_URL }}
        run: python ingest/ingest_weather.py

      - name: Run dbt (deps/run/test)
        run: |
          cd weather_dbt
          dbt debug --profiles-dir "$DBT_PROFILES_DIR"  # optional sanity check
          dbt deps
          dbt run
          dbt test
